using System;

namespace KartRider
{
	public class Kart
	{
		public static float AirFriction;
		public static float AnimalBoosterTime;
		public static float antiCollideBalance;
		public static float BackwardAccelForce;
		public static byte BikeRearWheel;
		public static float BoostAccelFactor;
		public static float BoostAccelFactorOnlyItem;
		public static float chargeBoostBySpeed;
		public static float CornerDrawFactor;
		public static float draftMulAccelFactor;
		public static int draftTick;
		public static float DragFactor;
		public static float driftBoostMulAccelFactor;
		public static int driftBoostTick;
		public static float DriftEscapeForce;
		public static float DriftGaguePreservePercent;
		public static float DriftLeanFactor;
		public static float DriftMaxGauge;
		public static float DriftSlipFactor;
		public static float DriftTriggerFactor;
		public static float DriftTriggerTime;
		public static float ForwardAccelForce;
		public static float FrontGripFactor;
		public static float GripBrakeForce;
		public static float ItemBoosterTime;
		public static byte ItemSlotCapacity;
		public static float Mass;
		public static float MaxSteerAngle;
		public static byte motorcycleType;
		public static float NormalBoosterTime;
		public static float RearGripFactor;
		public static float SlipBrakeForce;
		public static byte SpecialSlotCapacity;
		public static byte SpeedSlotCapacity;
		public static float StartBoosterTimeItem;
		public static float StartBoosterTimeSpeed;
		public static float StartForwardAccelForceItem;
		public static float StartForwardAccelForceSpeed;
		public static float SteerConstraint;
		public static float SteerLeanFactor;
		public static float SuperBoosterTime;
		public static float TeamBoosterTime;
		public static float TransAccelFactor;
		public static byte UseExtendedAfterBooster;
		public static byte UseTransformBooster;
		public static byte dualBoosterSetAuto;
		public static int dualBoosterTickMin;
		public static int dualBoosterTickMax;
		public static float dualMulAccelFactor;
		public static float dualTransLowSpeed;
		public static byte PartsEngineLock;
		public static byte PartsWheelLock;
		public static byte PartsSteeringLock;
		public static byte PartsBoosterLock;
		public static byte PartsCoatingLock;
		public static byte PartsTailLampLock;
		public static float chargeInstAccelGaugeByBoost;
		public static float chargeInstAccelGaugeByGrip;
		public static float chargeInstAccelGaugeByWall;
		public static float instAccelFactor;
		public static int instAccelGaugeCooldownTime;
		public static float instAccelGaugeLength;
		public static float instAccelGaugeMinUsable;
		public static float instAccelGaugeMinVelBound;
		public static float instAccelGaugeMinVelLoss;
		public static byte useExtendedAfterBoosterMore;
		public static int wallCollGaugeCooldownTime;
		public static float wallCollGaugeMaxVelLoss;
		public static float wallCollGaugeMinVelBound;
		public static float wallCollGaugeMinVelLoss;
		public static float modelMaxX;
		public static float modelMaxY;
	}
}
