//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauncherFile.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LauncherFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;FlyingPetSpec&gt;
        ///	&lt;id1 DragFactor=&apos;0&apos; ForwardAccelForce=&apos;0&apos; DriftEscapeForce=&apos;0&apos; CornerDrawFactor=&apos;0&apos; NormalBoosterTime=&apos;0&apos; ItemBoosterTime=&apos;0&apos; TeamBoosterTime=&apos;0&apos; StartForwardAccelForceItem=&apos;800&apos; StartForwardAccelForceSpeed=&apos;800&apos; /&gt;
        ///	&lt;id2 DragFactor=&apos;0&apos; ForwardAccelForce=&apos;0&apos; DriftEscapeForce=&apos;0&apos; CornerDrawFactor=&apos;0&apos; NormalBoosterTime=&apos;0&apos; ItemBoosterTime=&apos;0&apos; TeamBoosterTime=&apos;0&apos; StartForwardAccelForceItem=&apos;800&apos; StartForwardAccelForceSpeed=&apos;800&apos; /&gt;
        ///	&lt;id3 DragFactor=&apos;0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string FlyingPetSpec {
            get {
                return ResourceManager.GetString("FlyingPetSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;Item&gt;
        ///	&lt;Paint id=&apos;1&apos; /&gt;
        ///	&lt;Paint id=&apos;2&apos; /&gt;
        ///	&lt;Paint id=&apos;3&apos; /&gt;
        ///	&lt;Paint id=&apos;4&apos; /&gt;
        ///	&lt;Paint id=&apos;5&apos; /&gt;
        ///	&lt;Paint id=&apos;6&apos; /&gt;
        ///	&lt;Paint id=&apos;7&apos; /&gt;
        ///	&lt;Paint id=&apos;8&apos; /&gt;
        ///	&lt;Paint id=&apos;9&apos; /&gt;
        ///	&lt;Paint id=&apos;10&apos; /&gt;
        ///	&lt;Paint id=&apos;11&apos; /&gt;
        ///	&lt;Paint id=&apos;12&apos; /&gt;
        ///	&lt;Paint id=&apos;13&apos; /&gt;
        ///	&lt;Paint id=&apos;14&apos; /&gt;
        ///	&lt;Paint id=&apos;15&apos; /&gt;
        ///	&lt;Paint id=&apos;16&apos; /&gt;
        ///	&lt;Paint id=&apos;17&apos; /&gt;
        ///	&lt;Paint id=&apos;20&apos; /&gt;
        ///	&lt;Paint id=&apos;22&apos; /&gt;
        ///	&lt;Paint id=&apos;23&apos; /&gt;
        ///	&lt;Paint id=&apos;24&apos; /&gt;
        ///	&lt;Paint id=&apos;26&apos; /&gt;
        ///	&lt;Paint id=&apos;27&apos; /&gt;
        ///	&lt;Paint id=&apos;28&apos; /&gt;
        ///	&lt;Paint id=&apos;29&apos; /&gt;
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;KartSpec&gt;
        ///	&lt;id0 draftMulAccelFactor=&apos;1.1&apos; draftTick=&apos;2000&apos; driftBoostMulAccelFactor=&apos;1.4&apos; driftBoostTick=&apos;500&apos; chargeBoostBySpeed=&apos;350&apos; SpeedSlotCapacity=&apos;2&apos; ItemSlotCapacity=&apos;2&apos; SpecialSlotCapacity=&apos;1&apos; UseTransformBooster=&apos;True&apos; motorcycleType=&apos;False&apos; BikeRearWheel=&apos;True&apos; Mass=&apos;100&apos; AirFriction=&apos;3&apos; DragFactor=&apos;0.667&apos; ForwardAccelForce=&apos;2304&apos; BackwardAccelForce=&apos;1825&apos; GripBrakeForce=&apos;2070&apos; SlipBrakeForce=&apos;1415&apos; MaxSteerAngle=&apos;10&apos; SteerConstraint=&apos;24.61&apos; FrontGripFacto [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string KartSpec {
            get {
                return ResourceManager.GetString("KartSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;NewKart&gt;
        ///	&lt;Kart id=&apos;1&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;2&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;3&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;4&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;5&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;6&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;7&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;8&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;9&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;10&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;11&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;12&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;13&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;14&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;15&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;16&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;17&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;18&apos; sn=&apos;0&apos; /&gt;
        ///	&lt;Kart id=&apos;19&apos; sn=... 的本地化字符串。
        /// </summary>
        public static string NewKart {
            get {
                return ResourceManager.GetString("NewKart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PartsData&gt;
        ///  &lt;Kart id=&quot;1096&quot; sn=&quot;0&quot; Item_Id1=&quot;0&quot; Grade1=&quot;0&quot; PartsValue1=&quot;0&quot; Item_Id2=&quot;0&quot; Grade2=&quot;0&quot; PartsValue2=&quot;0&quot; Item_Id3=&quot;0&quot; Grade3=&quot;0&quot; PartsValue3=&quot;0&quot; Item_Id4=&quot;0&quot; Grade4=&quot;0&quot; PartsValue4=&quot;0&quot; partsCoating=&quot;0&quot; partsTailLamp=&quot;0&quot; /&gt;
        ///  &lt;Kart id=&quot;1097&quot; sn=&quot;0&quot; Item_Id1=&quot;0&quot; Grade1=&quot;0&quot; PartsValue1=&quot;0&quot; Item_Id2=&quot;0&quot; Grade2=&quot;0&quot; PartsValue2=&quot;0&quot; Item_Id3=&quot;0&quot; Grade3=&quot;0&quot; PartsValue3=&quot;0&quot; Item_Id4=&quot;0&quot; Grade4=&quot;0&quot; PartsValue4=&quot;0&quot; partsCoating=&quot;0&quot; partsTailLamp=&quot;0&quot; /&gt;
        ///  &lt;Kart id= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string PartsData {
            get {
                return ResourceManager.GetString("PartsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;RandomTrack&gt;
        ///	&lt;allitem Track=&apos;forest_I01&apos; /&gt;
        ///	&lt;allitem Track=&apos;forest_I02&apos; /&gt;
        ///	&lt;allitem Track=&apos;forest_I03&apos; /&gt;
        ///	&lt;allitem Track=&apos;forest_I04&apos; /&gt;
        ///	&lt;allitem Track=&apos;forest_I05&apos; /&gt;
        ///	&lt;allitem Track=&apos;forest_I06&apos; /&gt;
        ///	&lt;allitem Track=&apos;forest_I07&apos; /&gt;
        ///	&lt;allitem Track=&apos;forest_I09&apos; /&gt;
        ///	&lt;allitem Track=&apos;desert_I01&apos; /&gt;
        ///	&lt;allitem Track=&apos;desert_I10&apos; /&gt;
        ///	&lt;allitem Track=&apos;desert_I02&apos; /&gt;
        ///	&lt;allitem Track=&apos;desert_I11&apos; /&gt;
        ///	&lt;allitem Track=&apos;desert_I03&apos; /&gt;
        ///	&lt;allitem Track=&apos;desert_I04&apos; /&gt;
        ///	&lt;allitem T [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string RandomTrack {
            get {
                return ResourceManager.GetString("RandomTrack", resourceCulture);
            }
        }
    }
}
